name: Deploy

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am UTC
  push:
    branches:
      - main
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  depoly:
    name: Serverless
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    strategy:
      matrix:
        node: [ 16 ]
        platform: [ubuntu-latest]
    steps:
      - name: Setup os name to lowercase
        id: os-name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ runner.os }}

      - name: Split string
        uses: jungwinter/split@v2
        id: split
        with:
          separator: '/'
          msg: ${{ github.ref }}

      - name: Checkout ${{ steps.split.outputs._2 }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.split.outputs._2 }}

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Setup Serverless
        uses: teakowa/setup-serverless@v2
        with:
          provider: tencent
        env:
          TENCENT_APPID: ${{ secrets.TENCENTCLOUD_APP_ID }}
          TENCENT_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY}}
          SERVERLESS_PLATFORM_VENDOR: tencent

      - name: Deploy Serverless
        run: sls deploy

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs:
      - depoly
    steps:
      - name: Split Version or Branch
        uses: jungwinter/split@v2
        id: split
        with:
          separator: '/'
          msg: ${{ github.ref }}

      - name: Checkout ${{ steps.split.outputs._2 }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.split.outputs._2 }}

      - name: Lark Notification
        run: |
          curl '${{ secrets.SERVICE_UPDATES_ECHO_LARK_BOT_HOOK }}' \
             -H 'Content-Type: application/json' \
              -d '
              {
                "msg_type": "interactive",
                "card": {
                  "config": {
                    "wide_screen_mode": true
                },
                "header": {
                  "template": "green",
                  "title": {
                    "content": "✅  Production Deployment for ${{ github.repository }} ready!",
                    "tag": "plain_text"
                  }
                },
                "elements": [
                  {
                    "fields": [
                      {
                        "is_short": true,
                        "text": {
                          "content": "**🏷️  Version：**\n${{ steps.split.outputs._2 }}",
                          "tag": "lark_md"
                        }
                      },
                      {
                        "is_short": true,
                        "text": {
                          "content": "**🚧  Stage：**\n[Production](https://github.com/${{ github.repository }}/deployments/activity_log?environment=Production)",
                          "tag": "lark_md"
                        }
                      }
                    ],
                    "tag": "div"
                  },
                  {
                    "fields": [
                      {
                        "is_short": true,
                        "text": {
                          "content": "**🔨  Latest commit：**\n[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                          "tag": "lark_md"
                        }
                      },
                      {
                        "is_short": true,
                        "text": {
                          "content": "**🔍  Latest deploy log：**\n[${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                          "tag": "lark_md"
                        }
                      }
                    ],
                    "tag": "div"
                  },
                  {
                    "tag": "hr"
                  },
                  {
                    "tag": "markdown",
                    "content": "**服务开始滚动更新，预计几分钟后生效。**\n\n"
                  }
                ]
               }
              }'