name: Deploy

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am UTC
  push:
    branches:
      - main
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: XNXKTech/workflows/.github/workflows/node-build.yml@main
    with:
      environment: Production
      api_url: "https://starfire-bot.starubiquitous.com"
      eslint: false

  depoly:
    name: Serverless
    runs-on: ubuntu-latest
    needs:
      - build
    timeout-minutes: 10ß
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Serverless
        uses: teakowa/setup-serverless@v2
        with:
          provider: tencent
        env:
          TENCENT_APPID: ${{ secrets.TENCENTCLOUD_APP_ID }}
          TENCENT_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY}}
          SERVERLESS_PLATFORM_VENDOR: tencent

      - name: Deploy Serverless
        run: sls deploy

  notification:
    name: Deploy notification
    needs:
      - depoly
    uses: XNXKTech/workflows/.github/workflows/lark-notification.yml@main
    with:
      stage: Production
    secrets:
      LARK_WEBHOOK_URL: ${{ secrets.SERVICE_UPDATES_ECHO_LARK_BOT_HOOK }}